# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        build_type: [Debug, Release]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: clone wamr repo
        run: git clone https://github.com/bytecodealliance/wasm-micro-runtime.git wamr

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          mkdir inst
          mkdir build && cd build
          cmake ../wamr/product-mini/platforms/linux -DCMAKE_INSTALL_PREFIX=../inst -DCMAKE_BUILD_TYPE=${{ format( '{0}', matrix.build_type) }}
          make -j8
          make install
        
      - name: upload artifact
        uses: actions/upload-artifact@v1
        with:
          name: ${{ format( 'wamr-{0}', matrix.build_type) }}
          path: inst
          
      - name: archive folder
        run: |
          tar cvzf ${{ format( 'wamr-{0}.tar.gz', matrix.build_type) }} inst
          
      - name: publish release
        uses: gacts/upload-to-release@v1.0.1
        with:
          file: ${{ format( 'wamr-{0}.tar.gz', matrix.build_type) }}
          type: application/gzip
            
        
          
